version: "3.9"

services:
  api:
    build: 
      context: ./apps/api
    ports:
      - "8000:8000"
    environment:
      - WTA_API_URL=http://192.168.1.4:8000
      - DATABASE_URL=sqlite:////app/data/wta.db
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    volumes:
      - ./apps/api/data:/app/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.1.4:8000
    depends_on:
      - api
