"""sync_schema_is_test_and_more

Revision ID: 007262f99a4b
Revises: 20260405_0001
Create Date: 2026-04-13 23:58:32.186318
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '007262f99a4b'
down_revision = '20260405_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('wallet_transactions', sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'is_test')
    op.drop_column('payments', 'is_test')
    # ### end Alembic commands ###
