name = "winnertakesall"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "winner-takes-all-db"
database_id = "789d6ae3-5715-499c-b6b5-b069ec5eee51"

[[kv_namespaces]]
binding = "SESSIONS"
id = "788ab68ad9454e4ea7f2519b32792722"
